[pytest]
testpaths = tests e2e
python_files = test_*.py
python_classes = *Test* *Tests
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning:passlib.utils
    ignore::DeprecationWarning:jose.jwt
    ignore:datetime\.datetime\.utcnow\(\):DeprecationWarning
addopts = -v
