apiVersion: v1
kind: Service
metadata:
  name: user-dropoff-api
  namespace: user-dropoff
  labels:
    app: user-dropoff-api
spec:
  type: LoadBalancer
  selector:
    app: user-dropoff-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
